;;; pro-tabs-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pro-tabs.el

(autoload 'pro-tabs-open-new-tab "pro-tabs" "\
Open new tab to the right; if `dashboard-open' exists, call it." t)
(autoload 'pro-tabs-close-tab-and-buffer "pro-tabs" "\
Kill current buffer and its tab." t)
(defvar pro-tabs-mode nil "\
Non-nil if Pro-Tabs mode is enabled.
See the `pro-tabs-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `pro-tabs-mode'.")
(custom-autoload 'pro-tabs-mode "pro-tabs" nil)
(autoload 'pro-tabs-mode "pro-tabs" "\
Toggle pro-tabs everywhere.

This is a global minor mode.  If called interactively, toggle the
`Pro-Tabs mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='pro-tabs-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "pro-tabs" '("pro-tabs-"))

;;; End of scraped data

(provide 'pro-tabs-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pro-tabs-autoloads.el ends here
